apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  labels:
    name: tensorflow
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30088
    protocol: TCP
    targetPort: 8888
    name: http
  selector:
    app: tensorflow
