apiVersion: v1
kind: Service
metadata:
  name: tensorflow
  labels:
    name: tensorflow
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    name: http
  selector:
    app: tensorflow
