apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-volume
spec:
  selector:
    matchLabels:
      app: nginx
      volume: emptyDir
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        volume: emptyDir
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-vol
      volumes:
      - name: nginx-vol
        emptyDir: {}
