(define (make-account balance secret)
  (define (withdraw amount) 
    (if (>= balance amount) 
      (begin (set! balance (- balance amount)) balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount)) balance)
  (define (dispatch password m)
    (if (eqv? password secret)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request: MAKE-ACCOUNT" m)))
      (error "Incrorrect password")
      ))
  dispatch
  )

(define acc (make-account 100 'secret-pass))
((acc 'sec 'withdraw) 40)
((acc 'secret-pass 'withdraw) 10)